name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Windows runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Update to the desired Python version

      # Step 3: Upgrade pip to ensure compatibility with wheels
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      # Step 4: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install setuptools  # Install setuptools explicitly (includes distutils)
          pip install -r requirements.txt  # Install all dependencies from requirements.txt

      # Step 5: Set up Rust for building tokenizers package (if needed)
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 'stable'  # Installs the latest stable version of Rust

      # Step 6: Run deployment script
      - name: Run deployment script
        run: |
          python deploy_script.py  # Adjust to your specific deployment logic
