name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Change to Windows runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python (Make sure to use the correct Python version)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Update to the desired Python version

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install all dependencies from requirements.txt

      # Step 4: Run deployment script
      - name: Run deployment script
        run: |
          # Insert your deployment commands here
          python deploy_script.py  # Adjust to your specific deployment logic
